// <auto-generated />
namespace ManageThesis_Project.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class init_point : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(init_point));
        
        string IMigrationMetadata.Id
        {
            get { return "202405091602156_init_point"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
